Fix from_generator to use from_tensor_slices instead of from_generator.
When using from_generator, the following error raised when runnning `fit` method.

    ValueError: Cannot take the length of shape with unknown rank.